### ISSUE TITLE
Unsupported type Message 12 : Addressed Safety Related Message

### ISSUE THREAD

**Issue by TwinTurbine** [chrisadie/node-red-contrib-ais-decoder#29]
Would it be much trouble to implement decoding of message 12; Addressed Safety Related Message? It would be be very useful to me but I don't think I'll manage to implement it myself. Regards!

**Comment by chrisadie** [comment]
If you have an example (or - better - several examples) of such messages, I can certainly do that.

**Comment by TwinTurbine** [comment]
Hi Chris,

That sounds great! Below you can find a few examples.


!AIVDM,1,1,,A,<000960JQig41234567hijklmnPP,0*6B
Contains the free text message ”ABCDEFG0123456"

***@***.***,0*75
***@***.******@***.***,4*5F
Contains the message ”ABC012” as well as some binary application data.

***@***.***@2E1bREPN,0*02
***@***.***,0*0B
Contains some binary application data but no text message.

https://www.maritec.co.za/aisvdmvdodecoding <https://www.maritec.co.za/aisvdmvdodecoding> manages (almost) to the decode them fully. For message no 2 it cannot decode the free text, only the application data.

Regards,

Andreas

**Comment by chrisadie** [comment]
The second and third examples you gave are garbled for some reason. But I've used the first one to implement type 12 decoding in version 1.2.3. (I've also implemented message type 14 in that release.)

So, if you could test out release 1.2.3, that would be great.

I will close this issue for now.

Regards
Chris

**Comment by TwinTurbine** [comment]
Thanks Chris for sorting it out so quickly! I've recently tried release 1.2.3 and it seems to perform as anticipated. It decodes the messages very similar to the Maritec online decoder, but not identically. While Maritec outputs "@" 1.2.3 outputs white spaces. But it's not a big deal.

Message 2 & 3 isn't really garbled as they contains some binary encoded data in the message part. But I cannot (yet) verify whether or not that data is decoded correctly. 

Regards,
