### ISSUE TITLE
Inappropriate conversion of @ to space characters

### ISSUE THREAD

**Issue by chrisadie** [chrisadie/node-red-contrib-ais-decoder#31]
From issue 30:

> Using the ais decoder with the following message:
> 
> !AIVDM,2,1,1,A,<000960JQih@lsmos00Q;>t9Dd:9GiL>eaww38231jihhP058;@im10B,0*18
> !AIVDM,2,2,1,A,5@2E;2REtFwv=1@Phi0,2*17
> 
> will yield this string:
> 
> 4;57;  !KN<IT,JIW1\N-)??CHBCA2100  EHKP15A REPBUKB"U<V?>MAP 01
> 
> When it should be decoded as the following instead:
> 
> 4;57;@@!KN<IT,JIW1\N-)??CHBCA2100 @EHKP15A@REPBUKB"U<V?>MAP 01
> 
> So not all of the blankspaces should be translated into @ chars, but some of them.

**Comment by chrisadie** [comment]
According to [Eric Raymond's guide](https://gpsd.gitlab.io/gpsd/AIVDM.html) to decoding AIS messages,

> According to the standard, trailing unused characters in six-bit fields will be represented by "@" (six-bit zero); however, real-world encoders are not careful about this and often have nonzero garbage after the "@". The terminating "@" should not be considered part of the text, and any non-"@" characters after it should be discarded. It is also common to space-fill short fields such as ship and station name, so a decoder should strip trailing spaces after stripping at-signs and the garbage after them.

I have seen messages where a ship name string contains embedded @ signs - for instance `SEA@GLEANER`. In this case, it's clearly inappropriate to strip everything after the first @ sign.

Therefore, (in version 1.2.4) the decoder replaces any @ signs with spaces, then removes any trailing spaces. This transformation is applied to the following message properties:

- [msg.payload.name](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.name)
- [msg.payload.callsign](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.callsign)
- [msg.payload.destination](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.destination)
- [msg.payload.vendorId](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.vendorId)
- [msg.payload.europeanVesselIdentificationNumber](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.europeanVesselIdentificationNumber)
- [msg.payload.textMessage](https://github.com/chrisadie/node-red-contrib-ais-decoder/wiki/msg.payload.textMessage)

However, it's probably not appropriate to replace @ with space in the case of the `textMessage` property.

**Comment by TwinTurbine** [comment]
Yes, I've read that formulation as well regarding stripping and discarding of garbled data after the @-sign but thats not really according to the ITU-R M.1371 (-5) standard if applied everywhere, as far as I understand. However, for vessel name, call sign and a few others it's seems reasonable as several @-signs can be used to indicate that a value is unavailable/default.

But as you conclude it the `textMessage` property might be wise to exclude from this treatment. If one for some reason would try to send an E-mail address that would also be affected negatively as well in this case, as far as I understand.

I realize that I could have formulated my problem description better in the first place but sometimes I takes a few turns back and forth before realizing what the problem really is about. Thanks again for looking into it.

**Comment by chrisadie** [comment]
Fixed in version 1.2.5.  The `msg.payload.textMessage` property is now decoded correctly: embedded @ characters are not converted to spaces. However, trailing spaces and @ characters are still removed.

**Comment by TwinTurbine** [comment]
Thanks Chris! I have just performed som basic testing and so far it seems to perform exactly as expected!
